# Generated by Django 5.0.4 on 2024-04-17 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.TextField(max_length=500)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.intent')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(max_length=500)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.intent')),
            ],
        ),
        migrations.DeleteModel(
            name='Prompt',
        ),
    ]
