# Generated by Django 5.0.4 on 2024-04-18 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_intent_pattern_response_delete_prompt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
