# Generated by Django 5.0.4 on 2024-04-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intent',
            name='tagname',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='pattern',
            field=models.TextField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='response',
            field=models.TextField(max_length=500, unique=True),
        ),
    ]
