# Generated by Django 5.0.4 on 2024-04-19 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_intent_tagname_alter_pattern_pattern_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=500, unique=True)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.intent')),
            ],
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
